#!/bin/sh

gitclone() {
  local b=$1
  shift
  git clone "$@" git@github.com:grwlf/${b}.git ||
    git clone "$@" https://github.com/grwlf/${b}
}

set -e

if test -d $HOME/.vim ; then
	mv $HOME/.vim $HOME/.vim.old
fi

mkdir $HOME/.vim
cd $HOME/.vim

mkdir bundle
cd bundle

git clone https://github.com/vim-scripts/a.vim
git clone https://github.com/vim-scripts/comments.vim
git clone https://github.com/vim-scripts/grep.vim
git clone https://github.com/ervandew/supertab
git clone https://github.com/tpope/vim-pathogen
git clone https://github.com/tpope/vim-surround

gitclone nerdtree -b local 
gitclone cyrvim
gitclone find.vim
gitclone cycletags.vim



